language: php
php:
  - 5.5
  - 5.6
  - hhvm
  - nightly
  
services:
  - mysql
  - redis-server

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer install --prefer-source --no-interaction

